#!/bin/bash

function update_nodejs {

  local LATEST="v4.4.7"
  local NPM_WANTED_VERSION="2.15.8"
  local NODE_URL=https://nodejs.org/dist/${LATEST}/node-${LATEST}-linux-x64.tar.gz

  if [ "$LATEST" = "v" ]; then
    echo "Could not retrieve node version information from $VERSION_URL"
    return 1
  fi

  # Update Node.js if necessary

  which node >/dev/null 2>&1 # update if node is not avalible
  if [ $? != 0 ] || [ $(node --version) != ${LATEST} ]; then
    # Download
    if ! curl -L -o ${OPENSHIFT_DATA_DIR}tmp.tgz $NODE_URL; then
      return 1
    fi

    # Remove old files
    rm -rf ${OPENSHIFT_DATA_DIR}.nodejs

    # Copy binaries
    mkdir ${OPENSHIFT_DATA_DIR}.nodejs
    tar -xvzf ${OPENSHIFT_DATA_DIR}tmp.tgz --strip-components=1 -C ${OPENSHIFT_DATA_DIR}.nodejs

    # Remove downloaded archive
    rm ${OPENSHIFT_DATA_DIR}tmp.tgz

    # Output result
    echo "Node.js updated to $(node --version) with npm $(npm --version)."
  fi

  # Update global npm if necessary

  if [ $NPM_WANTED_VERSION != $(npm --version) ]; then
    npm i -g npm@${NPM_WANTED_VERSION}
    echo "Npm updated to $(npm --version)."
  fi
}
